// Exchange rates action types
export const FETCH_EXCHANGE_RATES = 'FETCH_EXCHANGE_RATES';
export const FETCH_EXCHANGE_RATES_PENDING = 'FETCH_EXCHANGE_RATES_PENDING';
export const FETCH_EXCHANGE_RATES_SUCCESS = 'FETCH_EXCHANGE_RATES_SUCCESS';
export const FETCH_EXCHANGE_RATES_ERROR = 'FETCH_EXCHANGE_RATES_ERROR';

export const FETCH_PAST_EXCHANGE_RATES = 'FETCH_PAST_EXCHANGE_RATES';
export const FETCH_PAST_EXCHANGE_RATES_PENDING = 'FETCH_PAST_EXCHANGE_RATES_PENDING';
export const FETCH_PAST_EXCHANGE_RATES_SUCCESS = 'FETCH_PAST_EXCHANGE_RATES_SUCCESS';
export const FETCH_PAST_EXCHANGE_RATES_ERROR = 'FETCH_PAST_EXCHANGE_RATES_ERROR';

export const SELECT_EXCHANGE_RATES_BASE = 'SELECT_EXCHANGE_RATES_BASE';
export const SELECT_EXCHANGE_RATES_TIMER = 'SELECT_EXCHANGE_RATES_TIMER';

// NetInfo action types
export const SET_NETINFO_STATUS = 'SET_NETINFO_STATUS';

